"""Constrained autonomous white-hat orchestration."""

from vrp_hunt.agent.authorization import (
    LiveReconAuthorization,
    LiveReconAuthorizationError,
    LiveReconOperatorPolicy,
    authorize_live_recon,
    load_operator_policy,
)
from vrp_hunt.agent.approvals import (
    ApprovalGateError,
    ApprovalGateResult,
    ApprovalMode,
    ApprovalRequiredAction,
    apply_approval_gate,
    approval_required_actions,
    render_approval_prompt,
)
from vrp_hunt.agent.controller import AutonomousAgent
from vrp_hunt.agent.artifacts import (
    AgentArtifactBundle,
    ObservationArtifact,
    ObservationConversionError,
    artifact_bundle_from_agent_run,
    finding_from_observation,
    finding_report_from_observation,
    report_draft_from_finding,
)
from vrp_hunt.agent.browser import (
    BrowserWorkflow,
    BrowserWorkflowStep,
    build_owned_account_browser_workflow,
)
from vrp_hunt.agent.credentials import (
    CookieRef,
    CredentialSet,
    OwnedAccount,
    OwnedTestObject,
    SecretRef,
)
from vrp_hunt.agent.evidence import (
    EvidenceCapture,
    EvidenceCaptureError,
    HttpEvidenceExchange,
)
from vrp_hunt.agent.executor import ActionRunner, DryRunRunner, RegisteredActionRunner
from vrp_hunt.agent.iteration import (
    RankedReconTarget,
    ReconIterationSummary,
    build_recon_iteration_summary,
    write_recon_iteration_outputs,
)
from vrp_hunt.agent.models import (
    ActionBudget,
    ActionPolicyDecision,
    AgentAction,
    AgentActionType,
    AgentObservation,
    AgentPlan,
    AgentRunResult,
    AutonomyPolicy,
    BrainSuggestion,
    BudgetState,
)
from vrp_hunt.agent.planner import (
    AgentBrain,
    HeuristicBrain,
    ModelBrain,
    StaticModelClient,
    StructuredModelClient,
    build_agent_plan,
    build_offline_analysis_plan,
)
from vrp_hunt.agent.policy import apply_budget, evaluate_action
from vrp_hunt.agent.providers import (
    ModelProviderError,
    ModelProviderName,
    OpenAIResponsesClient,
    build_agent_brain,
)
from vrp_hunt.agent.runners import (
    ApprovedSubprocessRunner,
    LiveReconRunner,
    SafeOfflineRunner,
    SafeValidationRunner,
    build_safe_offline_runner,
    build_safe_validation_runner,
)
from vrp_hunt.agent.submission import SubmissionAssistance, build_submission_assistance

__all__ = [
    "ActionBudget",
    "ActionPolicyDecision",
    "ActionRunner",
    "AgentAction",
    "AgentArtifactBundle",
    "AgentActionType",
    "AgentBrain",
    "AgentObservation",
    "AgentPlan",
    "AgentRunResult",
    "AutonomousAgent",
    "AutonomyPolicy",
    "ApprovalGateError",
    "ApprovalGateResult",
    "ApprovalMode",
    "ApprovalRequiredAction",
    "BrainSuggestion",
    "BrowserWorkflow",
    "BrowserWorkflowStep",
    "BudgetState",
    "CredentialSet",
    "CookieRef",
    "DryRunRunner",
    "EvidenceCapture",
    "EvidenceCaptureError",
    "HeuristicBrain",
    "HttpEvidenceExchange",
    "LiveReconRunner",
    "LiveReconAuthorization",
    "LiveReconAuthorizationError",
    "LiveReconOperatorPolicy",
    "ModelBrain",
    "ModelProviderError",
    "ModelProviderName",
    "OpenAIResponsesClient",
    "ObservationArtifact",
    "ObservationConversionError",
    "OwnedAccount",
    "OwnedTestObject",
    "ApprovedSubprocessRunner",
    "RankedReconTarget",
    "RegisteredActionRunner",
    "ReconIterationSummary",
    "SafeValidationRunner",
    "SecretRef",
    "StaticModelClient",
    "StructuredModelClient",
    "SubmissionAssistance",
    "SafeOfflineRunner",
    "apply_budget",
    "apply_approval_gate",
    "approval_required_actions",
    "artifact_bundle_from_agent_run",
    "authorize_live_recon",
    "build_agent_plan",
    "build_agent_brain",
    "build_offline_analysis_plan",
    "build_owned_account_browser_workflow",
    "build_recon_iteration_summary",
    "build_safe_offline_runner",
    "build_safe_validation_runner",
    "build_submission_assistance",
    "evaluate_action",
    "finding_from_observation",
    "finding_report_from_observation",
    "load_operator_policy",
    "report_draft_from_finding",
    "render_approval_prompt",
    "write_recon_iteration_outputs",
]
